### ISSUE TITLE
Exception in Application start method Mac OS X 10.10.5

### ISSUE THREAD

**Issue by mintwzy** [spheenik/clarity-analyzer#1]
Hi @spheenik , I try to compile and run the code with the following configuration:
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T19:57:37+08:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```
The compilation is fine, but when I run it with
```
java -jar target/analyzer.one-jar.jar
```
It gives me the exception
```
Exception in Application start method
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
	at com.sun.javafx.application.LauncherImpl$$Lambda$2/1394438858.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Cannot load skadistats.clarity.analyzer.main.main
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:89)
	at com.airhacks.afterburner.views.FXMLView.initializeFXMLLoader(FXMLView.java:96)
	at com.airhacks.afterburner.views.FXMLView.getView(FXMLView.java:108)
	at skadistats.clarity.analyzer.Main.start(Main.java:18)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
	at com.sun.javafx.application.LauncherImpl$$Lambda$53/83782501.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/637753910.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$51/1115276959.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/664341745.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: javafx.fxml.LoadException: Error resolving onAction='#actionOpen', either the event handler is not in the Namespace or there is an error in the script.
file:/target/analyzer.one-jar.jar!/main/analyzer.jar!/skadistats/clarity/analyzer/main/main.fxml:26

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.access$100(FXMLLoader.java:104)
	at javafx.fxml.FXMLLoader$Element.processEventHandlerAttributes(FXMLLoader.java:606)
	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:766)
	at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2827)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2536)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2445)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2413)
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:87)
	... 13 more
```
You have any ideas on this? Thanks a lot!

**Comment by mintwzy** [comment]
Thanks for the quick fix!
