### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Wondermarin** [spheenik/clarity-analyzer#12]
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project clarity-analyzer: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]`

**Comment by ravich3373** [comment]
@Wondermarin did you resolve this? can you please share the solution.

**Comment by tisttsf** [comment]
> @Wondermarin did you resolve this? can you please share the solution.

I have the same issue in building.
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.skadistats:clarity-analyzer >-------------------
[INFO] Building clarity-analyzer 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ clarity-analyzer ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ clarity-analyzer ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to W:\cl\clarity-analyzer\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.628 s
[INFO] Finished at: 2020-11-24T00:37:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project clarity-analyzer: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
How to solve that?

**Comment by ravich3373** [comment]
I am able to resolve this after removing openjdk 11 and installing oracle jdk 8 as per [this link](https://askubuntu.com/questions/430434/replace-openjdk-with-oracle-jdk-on-ubuntu), @tisttsf  hope this heps you.

**Comment by tisttsf** [comment]
> I am able to resolve this after removing openjdk 11 and installing oracle jdk 8 as per [this link](https://askubuntu.com/questions/430434/replace-openjdk-with-oracle-jdk-on-ubuntu), @tisttsf hope this heps you.

@ravich3373 I do this on win10 (reinstall jdk to the newest version).And I'm be able to build using `mvn package`,start analyzer program from command  ` java -jar target\analyzer.one-jar.jar`.However, I cannot open or access any .dem files,which are the replay files. Here are the errors log in the command line and interface status:
```
# java -jar target\analyzer.one-jar.jar
01:22:32.277 INFO     entity table selection from null to (8)
01:22:59.188 ERROR    Runner thread crashed
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[na:1.8.0_271]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[na:1.8.0_271]
        at skadistats.clarity.processor.runner.ControllableRunner$1.doLoopControl(ControllableRunner.java:64) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:35) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.runner.ControllableRunner$LockingLoopController.doLoopControl(ControllableRunner.java:160) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:131) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.runner.ControllableRunner.lambda$runWith$0(ControllableRunner.java:238) ~[clarity-2.5-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_271]
01:22:59.731 INFO     entity table selection from (7861) to null
01:22:59.733 INFO     entity table selection from null to (0)
01:25:17.596 ERROR    Runner thread crashed
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[na:1.8.0_271]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[na:1.8.0_271]
        at skadistats.clarity.processor.runner.ControllableRunner$1.doLoopControl(ControllableRunner.java:64) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:35) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.runner.ControllableRunner$LockingLoopController.doLoopControl(ControllableRunner.java:160) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:131) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39) ~[clarity-2.5-SNAPSHOT.jar:na]
        at skadistats.clarity.processor.runner.ControllableRunner.lambda$runWith$0(ControllableRunner.java:238) ~[clarity-2.5-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_271]
01:25:18.196 INFO     entity table selection from (0) to null
01:25:18.198 INFO     entity table selection from null to (0)
```
![gui_ana](https://user-images.githubusercontent.com/4705133/100775176-e2580200-343d-11eb-8b73-78ff1d63abfa.PNG)

**Comment by atakajlo** [comment]
I build with such dependencies on openjdk-11
https://github.com/spheenik/clarity-analyzer/issues/15#issuecomment-910212440
