### ISSUE TITLE
ReadMe Needs Updating

### ISSUE THREAD

**Issue by STRATZ-Ken** [spheenik/clarity-analyzer#13]
Following the ReadMe on Windows 10, Java 8.

```
C:\Git\clarity-analyzer-master>java -jar target\analyzer.one-jar.jar
Exception in thread "main" java.lang.NoClassDefFoundError: Stage
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:339)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.ClassNotFoundException: Stage
        at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:713)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more
```

**Comment by STRATZ-Ken** [comment]
Found the issue, was because I didnt have the JDK installed but the JSE.
