### ISSUE TITLE
cannot load recorded replays

### ISSUE THREAD

**Issue by nul0m** [spheenik/clarity-analyzer#14]
i'd like to find out what's wrong with the replays i've recorded being a spectator of some public matches. clarity analyzer crashes while playing them throwing the errors like this:
```
10:46:15.998 ERROR    Runner thread crashed
java.lang.ArrayIndexOutOfBoundsException: 7
	at skadistats.clarity.decoder.s2.Serializer.getUnpackerForFieldPath(Serializer.java:53) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.decoder.s2.field.FixedSubTableField.getUnpackerForFieldPath(FixedSubTableField.java:36) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.decoder.s2.Serializer.getUnpackerForFieldPath(Serializer.java:53) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.decoder.s2.S2DTClass.getUnpackerForFieldPath(S2DTClass.java:64) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:71) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:14) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.processor.entities.Entities.processEntityUpdate(Entities.java:394) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:327) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39) ~[clarity-2.5-20210108.182045-28.jar:na]
	at skadistats.clarity.processor.runner.ControllableRunner.lambda$runWith$0(ControllableRunner.java:238) ~[clarity-2.5-20210108.182045-28.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]

```

**Comment by spheenik** [comment]
replay is corrupt - or console recorded?

**Comment by nul0m** [comment]
sorry, i'm a bit confused now... is there a way to record a replay other than via console's `_record` command? or "console recorded" means smth else?

**Comment by spheenik** [comment]
see https://github.com/skadistats/clarity/issues/236#issuecomment-766325500
