### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by luttyest** [spheenik/clarity-analyzer#16]
Hi all,
       I am a novice trying to use the clarity analyzer as the data replay parser. I successfully use mvn package to compile the program but when I tried to run the program I encounter compile error.

JarClassLoader: Warning: javax/servlet/ServletRequest.class in lib/security-api-1.1-rev-1.jar is hidden by lib/servlet-api-3.0-alpha-1.jar (with different bytecode)
JarClassLoader: Warning: Null manifest from input stream associated with: lib/jaxrpc-api-1.1.jar
JarClassLoader: Warning: javax/servlet/ServletException.class in lib/jsp-api-2.1-rev-1.jar is hidden by lib/servlet-api-3.0-alpha-1.jar (with different bytecode)
JarClassLoader: Warning: javax/servlet/ServletRequest.class in lib/jsp-api-2.1-rev-1.jar is hidden by lib/servlet-api-3.0-alpha-1.jar (with different bytecode)
JarClassLoader: Warning: javax/servlet/ServletContext.class in lib/jsp-api-2.1-rev-1.jar is hidden by lib/servlet-api-3.0-alpha-1.jar (with different bytecode)
JarClassLoader: Warning: javax/servlet/ServletException.class in lib/jstl-api-1.2-rev-1.jar is hidden by lib/servlet-api-3.0-alpha-1.jar (with different bytecode)
JarClassLoader: Warning: javax/servlet/ServletRequest.class in lib/jstl-api-1.2-rev-1.jar is hidden by lib/servlet-api-3.0-alpha-1.jar (with different bytecode)
JarClassLoader: Warning: javax/servlet/ServletContext.class in lib/jstl-api-1.2-rev-1.jar is hidden by lib/servlet-api-3.0-alpha-1.jar (with different bytecode)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.Error: Unresolved compilation problem:
        The method launch(String[]) is undefined for the type Main

        at skadistats.clarity.analyzer.Main.main(Main.java:31)
        ... 6 more

Plz help, thanks!

**Comment by spheenik** [comment]
Using JDK 8 might help...

**Comment by steakscience** [comment]
@spheenik I'm currently using 1.8.0.291 but it's still failing to compile

**Comment by spheenik** [comment]
Please upload the resulting jar somewhere so I can have a look at it.
